// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:4d4f6551-f5d6-4207-bd6c-df0d948e29ca",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_DcllRQJhf",
    "aws_user_pools_web_client_id": "34npfotbr8nge3rn68qhhtur7l",
    "aws_user_files_s3_bucket": "amplifytestappstorage",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
